# 矩阵论

## 1.数据创建

In [1]:
import numpy as np
from scipy.linalg import *
from sympy import Matrix
import pprint
import matplotlib.pyplot as plt
import networkx as nx
import numpy.linalg

ModuleNotFoundError: No module named 'scipy'

### 1.1 手动数据输入

In [13]:
T1 = np.array([[0, 1, 0, 0, 1, 1, 0],
               [0, 0, 1, 0, 1, 0, 0],
               [0, 0, 0, 1, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 1],
               [0, 0, 0, 1, 0, 1, 1],
               [0, 0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0, 0]])
# A1 = np.mat()
# A1 = np.array()
print(T1)

[[0 1 0 0 1 1 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 1 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]


In [12]:
# 1-D array: 1 x 3 创建一维数组
one_dim_M11 = np.array([0,1,4])

# 1-D array
one_dim_M12 = np.array([[1, 2, 3]])

# one_dim_vec2 = np.array([4, 5, 6])
one_dim_M13 = np.array([[4,], [5,], [6,]])

print(f'one_dim_M11:\n{one_dim_M11}')
print(f'one_dim_M12:\n{one_dim_M12}')
print(f'one_dim_M13:\n{one_dim_M13}')

one_dim_M11:
[0 1 4]
one_dim_M12:
[[1 2 3]]
one_dim_M13:
[[4]
 [5]
 [6]]


In [11]:
# 2-D array: 2 x 3
two_dim_M21 = np.array([[1, 2, 3],
                        [4, 5, 6]])
# 创建多维数组
two_dim_M22 = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8]])
# 2-D array: 3 x 2
two_dim_M23 = np.array([[1, 2],
                        [3, 4],
                        [5, 6]])

print(f'two_dim_M21:\n{two_dim_M21}')
print(f'two_dim_M22:\n{two_dim_M22}')
print(f'two_dim_M23:\n{two_dim_M23}')

two_dim_M21:
[[1 2 3]
 [4 5 6]]
two_dim_M22:
[[1 2 3 4]
 [5 6 7 8]]
two_dim_M23:
[[1 2]
 [3 4]
 [5 6]]


### 1.2 自动数据输入

In [10]:
a1 = np.array(range(6), dtype = int)            # 创建整数类型的数组
a2 = np.arange(6, dtype = 'f')                  # 类似range,创建浮点型的数组
a3 = np.array(range(6), dtype = int, ndmin=2)   # 创建两个维度，数据类型是整数的数组
# 创建复数型的数组
a4 = np.arange(6, dtype = 'D')
# 输入的是几个维度，就自动生成几个维度的数组
a5 = np.array([range(6),range(6)],ndmin=0,dtype=float)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)

[0 1 2 3 4 5]
[0. 1. 2. 3. 4. 5.]
[[0 1 2 3 4 5]]
[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
[[0. 1. 2. 3. 4. 5.]
 [0. 1. 2. 3. 4. 5.]]


In [9]:
print(f'one1:\n{np.ones([1,2])}')           # 创建一个值均为1的1*2维ndarray对象
print(f'one2:\n{np.ones((3,3))}')           # 生成一个3x3全1的矩阵

one1:
[[1. 1.]]
one2:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(f'zeros1:\n{np.zeros((2, 2))}')
print(f'zeros2:\n{np.zeros((2, 2), dtype = bool)}')

In [8]:
print(f'full1:\n{np.full((3,3),2.1)}')     # 创建一个值均为7的3*3维ndarray对象

full1:
[[2.1 2.1 2.1]
 [2.1 2.1 2.1]
 [2.1 2.1 2.1]]


In [7]:
print(f'eye1:\n{np.eye(3)}')        # 等于 print(f'eye2:\n{np.eye(3, 3)}')
print(f'eye3:\n{np.eye(3, k=1)}')        # 向后面移动一位
print(f'identity1:\n{np.identity(3)}')

eye1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eye3:
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
identity1:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(f'random:\n{np.random.randint(0,10,(3,3))}')

### 1.3 数据属性以及转换 (打印矩阵的shape，ndim，size，dtype)

array函数
array.astype('xxx eg float32')  # 把矩阵中的数据改为float32类型
$array.sum()$       求和
$array.max()$       求最大值
$array.min()$       求最小值
$array.mean()$      求平均值

In [ ]:
print(np.array(range(3)))
print(np.array(range(3)).shape)
print(np.array(range(3)).ndim)
print(np.array(range(3)).size)
print(np.array(range(3)).dtype)
print(np.array(range(3)).astype(bool))       # 数据矩阵转化成bool类型的数据矩阵
print(~np.array(range(3)).astype(bool))      # 数据矩阵转化成bool类型的数据矩阵
print(np.array([False, True]).astype(int))   # 数据矩阵转化成int类型的数据矩阵

In [ ]:
print(np.arange(12).reshape(3, 4))

In [ ]:
print(np.arange(12).reshape(3, 4).shape)
print(np.arange(12).reshape(3, 4).ndim)
print(np.arange(12).reshape(3, 4).size)
print(np.arange(12).reshape(3, 4).dtype)

In [ ]:
print(np.arange(12).reshape(3, 4).T.shape)# a = a.T # 矩阵转置
print(np.arange(12).reshape(3, 4).T.ndim)
print(np.arange(12).reshape(3, 4).T.size)
print(np.arange(12).reshape(3, 4).T.dtype)

In [ ]:
# a = a[0,:] # 获取第一列——》向量   # a = a[:,0] # 获取第一行——》向量\

## 2 矩阵运算

In [ ]:
print('two_multi_res:\n %s' % (np.dot(two_dim_M21, two_dim_M23) ))
print('one_result_res\n %s' % (np.dot(one_dim_M12, one_dim_M13) ))

In [ ]:
Di = np.random.randint(0,10,(3,3))
print(f'Di:\n{Di}')
print(f'Di**2:\n{Di**2}')
print(f'Di**3:\n{Di**3}')

In [ ]:
# np.array.any()是或操作，任意一个元素为True，输出为True。
# np.array.all()是与操作，所有元素为True，输出为True
# x = (Mold == Mnew).all()

## 2.1 逻辑运算

In [ ]:
cond1 = np.array([1,  1, 1, 1,  0])
# cond1 = np.array([True, False, True, True, False])
cond2 = np.array([0, 1, 0, 1, 0])
# cond2 = np.array([False, True, False, True, False])
print(cond1)
print(cond2)

### 2.1.1.与运算:

In [ ]:
print('AND-operation')
print( np.logical_and(cond1, cond2) )
print( cond1 & cond2 )
# print( cond1 and cond2 )

### 2.1.2.或运算:

In [ ]:
print('OR-operation')
print( np.logical_or(cond1, cond2) )
print( cond1 |  cond2 )             # cond1 cond2 矩阵取或运算
# print( cond1 or cond2 )

### 2.1.3.非运算：

In [ ]:
print('NOT-operation')
print( np.logical_not(cond1) )
print( np.logical_not(cond2) )
print( ~np.logical_not(cond1) )
print( ~np.logical_not(cond2) )
# print( not cond1 )

### 2.1.4.异或运算:

In [ ]:
print( np.logical_xor(cond1, cond2) )
print( np.bitwise_xor(cond1, cond2) )
print( cond1 ^ cond2 )

[ True False  True False False]
[1 0 1 0 0]
[1 0 1 0 0]


In [ ]:
print(orth(np.array([[1,2,3],[2,1,3],[3,2,1]])))        # 计算正交基
print(np.dot(np.array([[1,2,3],[2,1,3],[3,2,1]]), orth(np.array([[1,2,3],[2,1,3],[3,2,1]]))))

#### jordan标准型

In [ ]:
#A = np.array([[3,1,0,0],[-4,-1,0,0],[6,2,0,-1],[-2,0,1,2]])
a = Matrix(np.array([[4,9,2], [3,5,7], [8,1,6]]))
P, Ja = a.jordan_form()
pprint.pprint(Ja)
pprint.pprint(P)

In [ ]:



G = nx.fast_gnp_random_graph(4, 0.5)
adj_matrix = nx.adjacency_matrix(G).todense()


# A1 = np.ones((4, 4))
# B = A1 - adj_matrix
# B = np.array(B, dtype=int)
# det_B = np.linalg.det(B)

# mat = np.array([[-1, 1, 0],
#               [-4, 3, 0],
#               [1, 0, 2]])

# mat = np.array([[0, 1, 0, 0],
#                 [0, 0, 1, 0],
#                 [0, 0, 0, 1],
#                 [0, 0, 0, 0]])

# eigenvalue, featurevector = np.linalg.eig(mat)

# print(mat)
# print(B)
print(adj_matrix)
# print(det_B)
# print("特征值：\n", eigenvalue)
# print("特征向量：\n", featurevector)
 adj_matrix = nx.adjacency_matrix(G).todense()

In [ ]:
n = 1000  # 1000 nodes
m = 5000  # 5000 edges
G = nx.gnm_random_graph(n, m, seed=5040)  # Seed for reproducibility
L = nx.normalized_laplacian_matrix(G)
e = np.linalg.eigvals(L.A)      # 获取特征值
print("Largest eigenvalue:", max(e))
print("Smallest eigenvalue:", min(e))
plt.hist(e, bins=100)           # histogram with 100 bins
plt.xlim(0, 2)                  # eigenvalues between 0 and 2
plt.show()

### 传递约简

In [ ]:
# #### Transitive reduction Function #### #
#   param:  matrix: Adjacency Matrix
#   return: A matrix that has been reduced in transitive
def transitive_reduction_matrix(dagx):
    matrix = np.array(nx.adjacency_matrix(dagx).todense())
    row, columns = matrix.shape
    # 行列式
    # assert (row == columns)
    # assert (columns == self.task_num)
    print("matrix shape is ({0},{1})".format(row, columns))
    i_test = np.eye(columns).astype(bool)
    i_matrix = matrix.astype(bool)
    D = np.power((i_matrix | i_test), columns)  # (M | I)^n
    D = D.astype(bool) & (~i_test)
    TR = matrix & (~(np.dot(i_matrix, D)))  # Tr = T ∩ （-（T . D））
    return nx.DiGraph(TR)

In [ ]:
#####################################
# todo Section_0: DAG Basic function
#####################################
# #### Gets the nodes in the ready state of the DAG #### #
def get_ready_node_list(temp_DAG_list, run_list, ready_list):
    temp_ready_list = [(ready_node_x[0], ready_node_x[1][0])for ready_node_x in ready_list]
    ret_list = []
    for temp_DAG_x in temp_DAG_list:
        ret_list += [(temp_DAG_x.graph['DAG_ID'], x) for x in temp_DAG_x.nodes(data=True) if
                     (len(list(temp_DAG_x.predecessors(x[0]))) == 0) and
                     ((temp_DAG_x.graph['DAG_ID'], x[0]) not in run_list) and
                     ((temp_DAG_x.graph['DAG_ID'], x[0]) not in temp_ready_list)]
    return ret_list



In [ ]:
from itertools import combinations
s = ['1','2','3']
for element in combinations(s,2):
    a = ''.join(element)
    print(a,end=' ')